config/routes.rb
Rails.application.routes.draw do
  resources :inventories do
    collection do
      get :barcodes
      get :search
    end
  end
  root 'inventories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :inventories
end

app/models/inventory.rb
require 'barby'
require 'barby/barcode/code_128'
require 'barby/outputter/png_outputter'

class Inventory < ApplicationRecord
  belongs_to :division
  delegate :name, to: :division, prefix: true, allow_nil: true

  def get_barcode
    file_path = Rails.root.join('public', barcode_name)
    barcode = Barby::Code128B.new("#{no_inventory}")
    blob = Barby::PngOutputter.new(barcode).to_png #Raw PNG data
    File.open(file_path, 'wb'){|f| f.write blob }
    barcode_name
  end

  def barcode_name
    "barcode-#{no_inventory}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  def barcodes
    @inventories = Inventory.all
  end

  def search
    @inventories = Inventory.where('no_inventory ILIKE ? OR name ILIKE ?', "#{params[:q]}%", "#{params[:q]}%")
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to root_url, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to root_url, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:name, :owner_name, :no_identity, :no_inventory, :division_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.slim
= simple_form_for @inventory do |f|
  - if @inventory.errors.any?
    #error_explanation
      h2 = "#{pluralize(@inventory.errors.count, "error")} prohibited this inventory from being saved:"
      ul
        - @inventory.errors.full_messages.each do |message|
          li = message

  .field
    = f.input :name
  .field
    = f.association :division, collection: Division.order(:name).pluck(:name, :id), include_blank: 'Pilih bagian'
  .field
    = f.input :owner_name
  .field
    = f.input :no_identity
  .field
    = f.input :no_inventory
  .actions 
    = f.submit 'Save', class: 'waves-effect waves-light btn', style: 'float: right'

app/views/inventories/_inventory_table.html.slim
table
  thead
    tr
      th Name
      th bagian
      th Owner name
      th No identity
      th No inventory
      th
      th
      th

  tbody
    - inventories.each do |inventory|
      tr
        td = inventory.name
        td = inventory.division_name
        td = inventory.owner_name
        td = inventory.no_identity
        td = inventory.no_inventory
        td = link_to 'Show barcode', inventory
        td = link_to 'Edit', edit_inventory_path(inventory)
        td = link_to 'Destroy', inventory, data: { confirm: 'Are you sure?' }, method: :delete

app/views/inventories/barcodes.html.slim
- @inventories.each do |inventory|
  div style="text-align: center; width: 200px; float: left"
    = image_tag "/#{inventory.get_barcode}"
    br
    = inventory.no_inventory

app/views/inventories/edit.html.slim
h3.header  Editing inventory
br
== render 'form'

= link_to 'Show', @inventory, class: 'waves-effect waves-light btn blue', style: 'margin-bottom: 20px'
= link_to 'Back', inventories_path, class: 'waves-effect waves-light btn red', style: 'margin-bottom: 20px'

app/views/inventories/index.html.slim
h1 Listing inventories

= form_tag search_inventories_path, method: :get, remote: true
  = text_field_tag :q, params[:q], placeholder: 'Search..', class: 'js-input-on-change', autofocus: true

.js-inventories
  = render 'inventory_table', inventories: @inventories

= link_to 'Show Barcodes', barcodes_inventories_path, class: 'waves-effect waves-light btn', style: 'margin-bottom: 20px; margin-top: 20px'
= link_to 'New Inventory', new_inventory_path, class: 'waves-effect waves-light red btn', style: 'margin-bottom: 20px; margin-top: 20px'

app/views/inventories/new.html.slim
h3.header New inventory
br
== render 'form'

= link_to 'Back', inventories_path, class: 'waves-effect waves-light btn red', style: 'margin-bottom: 20px'

app/views/inventories/search.js.erb
$('.js-inventories').html("<%= j(render 'inventory_table', inventories: @inventories) %>")

app/views/inventories/show.html.slim
div style="text-align: center"
  = image_tag '/barcode.png'
  br
  = @inventory.no_inventory
/ p#notice = notice

/ p
/   strong Name:
/   = @inventory.name
/ p
/   strong Owner name:
/   = @inventory.owner_name
/ p
/   strong No identity:
/   = @inventory.no_identity
/ p
/   strong No inventory:
/   = @inventory.no_inventory

/ = link_to 'Edit', edit_inventory_path(@inventory)
/ '  |
/ = link_to 'Back', inventories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventarisApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless (params[:id] && params[:action].eql?('show')) || params[:action].eql?('barcodes') %>
      <nav>
        <div class="container">
          <div class="nav-wrapper">
            <a href="/" class="brand-logo">Home</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li><a href="sass.html">Sass</a></li>
              <li><a href="badges.html">Components</a></li>
              <li><a href="collapsible.html">JavaScript</a></li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>

    <div class="container main">
      <%= yield %>
    </div>

    <% unless (params[:id] && params[:action].eql?('show')) || params[:action].eql?('barcodes') %>
      <footer class="page-footer">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Footer Content</h5>
              <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
          © 2014 Copyright Jasa Medivest
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
          </div>
        </div>
      </footer>
    <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>